// <auto-generated />
using System;
using EnglishAppWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnglishAppWeb.Migrations
{
    [DbContext(typeof(EnglishAppContext))]
    partial class EnglishAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnglishAppWeb.Models.Atividade", b =>
                {
                    b.Property<int>("AtividadeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Arquivo");

                    b.Property<DateTime>("DataEntrega");

                    b.Property<DateTime>("DataPostagem");

                    b.Property<string>("Nome");

                    b.Property<int>("Pontos");

                    b.HasKey("AtividadeId");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("EnglishAppWeb.Models.AtividadeAluno", b =>
                {
                    b.Property<int>("AtividadeId");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("AtividadeId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AtividadeAlunos");
                });

            modelBuilder.Entity("EnglishAppWeb.Models.Turma", b =>
                {
                    b.Property<int>("TurmaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo");

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.HasKey("TurmaId");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("EnglishAppWeb.Models.TurmaUsuario", b =>
                {
                    b.Property<int>("TurmaId");

                    b.Property<int>("UsuarioId");

                    b.HasKey("TurmaId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TurmaUsuarios");
                });

            modelBuilder.Entity("EnglishAppWeb.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.Property<int>("Tipo");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EnglishAppWeb.Models.AtividadeAluno", b =>
                {
                    b.HasOne("EnglishAppWeb.Models.Atividade", "Atividade")
                        .WithMany("AtividadeAluno")
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EnglishAppWeb.Models.Usuario", "Usuario")
                        .WithMany("AtividadeAluno")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EnglishAppWeb.Models.TurmaUsuario", b =>
                {
                    b.HasOne("EnglishAppWeb.Models.Turma", "Turma")
                        .WithMany("TurmaUsuario")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EnglishAppWeb.Models.Usuario", "Usuario")
                        .WithMany("TurmaUsuario")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
